export const LOGIN_USER_SUCCESS = 'AUTHENTICATION/LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'AUTHENTICATION/LOGIN_USER_FAIL';
export const LOGIN_USER_START = 'AUTHENTICATION/LOGIN_USER_START';
export const REGISTER_USER_SUCCESS = 'AUTHENTICATION/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'AUTHENTICATION/REGISTER_USER_FAIL';
export const REGISTER_USER_START = 'AUTHENTICATION/REGISTER_USER_START';

export const RESET_STATE = 'RESET_STATE';

export const WIKIPEDIA_SEARCH_START = 'WIKIPEDIA/SEARCH_START';
export const WIKIPEDIA_SEARCH_FAIL = 'WIKIPEDIA/SEARCH_FAIL';
export const WIKIPEDIA_SEARCH_SUCCESS = 'WIKIPEDIA/SEARCH_SUCCESS';